//go:build tools

// Code generated by shipbuilder init 1.21.2. DO NOT EDIT.

package ketch_forwarder

import (
	_ "github.com/vektra/mockery/v2"
	_ "go.ketch.com/tool/proto-nats/cmd/protoc-gen-nats"
	_ "go.ketch.com/tool/shipbuilder/cmd/shipbuilder"
	_ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
	_ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
