// Code generated by shipbuilder init 1.18.0. DO NOT EDIT.

package main

import (
	"github.com/ketch-com/ketch-forwarder/pkg/callback"
	"go.ketch.com/lib/orlop/v2/cmd"
)

func main() {
	cmd.Run("ketch-callback-mock", callback.Module)
}
