// Code generated by shipbuilder init 1.18.0. DO NOT EDIT.

package main

import (
	"github.com/ketch-com/ketch-forwarder/pkg/receiver"
	"go.ketch.com/lib/orlop/v2/cmd"
)

func main() {
	cmd.Run("controller-receiver-mock", receiver.Module)
}
