#!/usr/bin/env sh

# Code generated by shipbuilder init 1.18.0. DO NOT EDIT.

if [ ! -f "./scripts/check.sh" ]; then
  cd $(command dirname -- "$(command readlink -f "$(command -v -- "$0")")")/..
fi

if [ -f "package.json" ]; then
  . ./scripts/check.sh npm

  set -e

  $npm install
  $npm run build
else
  if [ -n "$(find . -regex ".*node_modules.*" -prune -o -name package.json -print)" ]; then
    . ./scripts/check.sh npm

    set -e

    find . -regex ".*node_modules.*" -prune -o -name package.json -execdir $npm install \; -execdir $npm run build \; -print
  fi
fi
