#!/usr/bin/env sh

# Code generated by shipbuilder init 1.21.0. DO NOT EDIT.

if [ ! -f "./scripts/check.sh" ]; then
  cd $(command dirname -- "$(command readlink -f "$(command -v -- "$0")")")/..
fi

. ./scripts/check.sh

if [ -d openapi ]; then
  check go jq yq swagger_cli shipbuilder

  export module=$($go mod edit -json | $jq -r .Module.Path)

  set -e

  echo "Merging all servers into openapi/servers/index.yaml..."
  $yq ea '. as $item ireduce ({}; . * $item )' openapi/servers/*.yaml openapi/servers/index.yaml > openapi/servers/index.yaml.bak
  mv openapi/servers/index.yaml.bak openapi/servers/index.yaml

  echo "Generating gateway indexes..."
  for i in parameters responses requestBodies schemas; do
    if [ -d "openapi/components/$i" ]; then
      echo "* openapi/components/$i/_index.yaml"
      find "openapi/components/$i" -type f -name '*.yaml' -not -name '_index.yaml' | xargs -I {} basename {} .yaml | xargs -I {} printf "{}:\n  \$ref: \"./{}.yaml\"\n" > "openapi/components/$i/_index.yaml"
    fi
  done

  servers=$(find openapi/servers -type f -name '*.yaml' -not -name 'index.yaml' | xargs -I {} basename {} .yaml)

  echo "Generating openapi definitions..."
  for i in $servers; do
    $swagger_cli bundle --outfile "openapi/${i}_gen.yaml" --type yaml "openapi/servers/$i.yaml"
  done

  $swagger_cli bundle --outfile openapi/index_gen.yaml --type yaml openapi/servers/index.yaml

  echo "Generating gateway stubs..."
  for i in $servers; do
    # Generate the gateway stub code
    echo "* openapi/${i}_gen.yaml -> gateway/${i}_{handlers,requests,responses}_gen.go"
    $shipbuilder generate \
      --go-handler "pkg/gateway/${i}_handlers_gen.go" --go-handler-package "${module}/pkg/gateway" \
      --go-requests "pkg/gateway/${i}_requests_gen.go" --go-requests-package "${module}/pkg/gateway" \
      --go-responses "pkg/gateway/${i}_responses_gen.go" --go-responses-package "${module}/pkg/gateway" \
      "openapi/${i}_gen.yaml"
  done

  echo "* openapi/index_gen.yaml -> gateway/types_gen.go"
  $shipbuilder generate \
    --go-types pkg/gateway/types_gen.go --go-types-package "${module}/pkg/gateway" \
    openapi/index_gen.yaml
fi
