#!/usr/bin/env sh

# Code generated by shipbuilder init 1.18.0. DO NOT EDIT.

if [ ! -f "./scripts/check.sh" ]; then
  cd $(command dirname -- "$(command readlink -f "$(command -v -- "$0")")")/..
fi

protos=$(find pkg -name \*.proto)
if [ -n "$protos" ]; then
  . ./scripts/check.sh protoc protoc_gen_go protoc_gen_go_grpc protoc_gen_nats

  set -e

  echo "Generating protobuf..."

  for i in $protos; do
    echo "* $i"
    $protoc --proto_path=pkg --go_out=pkg --go_opt=paths=source_relative --go-grpc_out=pkg --nats_out=pkg --go-grpc_opt=paths=source_relative "$i"
  done
fi
