#!/usr/bin/env sh

# Code generated by shipbuilder init 1.19.1. DO NOT EDIT.

if [ ! -f "./scripts/check.sh" ]; then
  cd $(command dirname -- "$(command readlink -f "$(command -v -- "$0")")")/..
fi

. ./scripts/check.sh

if [ -d "./docker/smoketest" ]; then
  check docker

  # Run the build script
  ./scripts/build.sh linux

  set -e

  # Spin up the docker compose with the smoketest profile
  $docker compose --profile smoketest up --build --force-recreate --quiet-pull --attach smoketest

  # Tear down the docker compose
  $docker compose --profile smoketest down --remove-orphans

  # Prune docker compose setup if specified
  if [ "$1" = "--prune" ]; then
    $docker container prune --force >/dev/null 2>&1
    $docker volume prune --force >/dev/null 2>&1
    $docker image prune --force --all >/dev/null 2>&1
    $docker network prune --force >/dev/null 2>&1
  fi
else
  echo "no smoketest available"
  exit 1
fi
